export const AppRoute = {
  home: "/",
  login: "/login",
  signup: "/signup",
  users: "/users",
  userCreate: "/users/create",
  userDetails: "/users/[id]",
  userUpdate: "/users/[id]/update",
  roles: "/roles",
  roleCreate: "/roles/create",
  roleDetails: "/roles/[id]",
  roleUpdate: "/roles/[id]/update",
  reviews: "/reviews",
  reviewCreate: "/reviews/create",
  reviewDetails: "/reviews/[id]",
  reviewUpdate: "/reviews/[id]/update",
  siteSettings: "/site-settings",
  doctorProfile: "/doctor-profile",
  packagesPageSettings: "/packages-page-settings",
  settings: "/settings",
  settingsPassword: "/settings/password",
} as const;
