export enum EntityName {
  USER = "User",
  ROLE = "Role",
  PERMISSION = "Permission",
  REVIEW = "Review",
  SITE_SETTINGS = "SiteSettings",
  DOCTOR_PROFILE = "DoctorProfile",
  PACKAGES_PAGE_SETTINGS = "PackagesPageSettings",
  CAMPAIGN = "Campaign",
  RECIPE_CATEGORY = "RecipeCategory",
  RECIPE_FOOD_GROUP = "RecipeFoodGroup",
  RECIPE = "Recipe",
  VIDEO = "Video",
  FAQ_SECTION = "FaqSection",
  FAQ_ITEM = "FaqItem",
  PACKAGE = "Package",
  CLIENT = "Client",
  STAFF = "Staff",
  CLIENT_MEASUREMENT = "ClientMeasurement",
  NUTRITION_ASSESSMENT = "NutritionAssessment",
  NUTRITION_CALCULATION = "NutritionCalculation",
  CLIENT_INTERACTION = "ClientInteraction",
  DASHBOARD = "Dashboard",
}
